#!/bin/sh
IFACE=usb0
DAEMON=/usr/sbin/udhcpd
NAME=chumby-otg-debug
DESC="chumby OTG debug mode"
PIDFILE="/var/run/chumby-otg-dhcp.pid"
ARGS="/etc/udhcpd.conf"

test -f $DAEMON || exit 0

set -e

case "$1" in
    start)
        echo -n "starting $DESC: $NAME... "
        test -d /var/lib/misc/ || mkdir /var/lib/misc/
        modprobe g_ether
        udevadm settle
        ifconfig $IFACE up 10.0.88.1 netmask 255.255.255.0
        $DAEMON $ARGS
        echo "done."
        ;;
    stop)
        echo -n "stopping $DESC: $NAME... "
        if [ -e $PIDFILE ]
        then
            kill $(cat $PIDFILE)
        fi
        rmmod g_ether
        echo "done."
        ;;
    status)
        echo -n "dnsmasq "
        if [ -e "$PIDFILE" ]; then
                PID=$(cat $PIDFILE)
                echo "($PID) is running"
        else
                echo "is not running"
                exit 1
        fi
        ;;
    restart)
        echo "restarting $DESC: $NAME... "
        $0 stop
        $0 start
        echo "done."
        ;;
    reload)
        echo -n "reloading $DESC: $NAME... "
        killall -HUP $(basename ${DAEMON})
        echo "done."
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart|reload}"
        exit 1
        ;;
esac

exit 0
