require u-boot.inc
PR ="r2"
RPROVIDES = "virtual/bootloader"
#DEFAULT_PREFERENCE = "-1"

SRC_URI = "file://uboot_src.tgz \
        file://0001-pxa910-add-88SV331xV5-core-support.patch \
        file://0002-pxa910-add-pxa168-soc-support.patch \
        file://0003-pxa910-reduce-size-of-UBOOT.patch \
        file://0004-pxa910-add-tavorevb-board-support.patch \
        file://0005-pxa910-enable-nand-with-bbm-support.patch \
        file://0006-pxa910-enable-multi-net-and-smc91111.patch \
        file://0007-pxa910-enable-ns16550-and-reserve-a-log-buf-to-debu.patch \
        file://0008-pxa910-add-usb-over-ethernet-download-support.patch \
        file://0009-pxa910-sync-onenand-with-kernel.patch \
        file://0010-pxa910-add-yaffs-img-write-for-nand.patch \
        file://0011-pxa910-add-onenand-dump-function.patch \
        file://0012-pxa910-add-yaffs-img-write-for-onenand.patch \
        file://0013-pxa910-add-img-write-progress-showing.patch \
        file://0014-pxa910-add-onenand-cleanmarker-write-for-JFFS2.patch \
        file://0015-pxa910-sync-onenand-erase-behavior-with-nand.patch \
        file://0016-pxa910-add-tftp-download-via-network-to-memory.patch \
        file://0017-pxa910-add-boot-zImage-from-memory.patch \
        file://0018-pxa910-add-ping-function.patch \
        file://0019-pxa168-add-aspenite-board-support.patch \
        file://0020-pxa168-add-zylonite2-board-configure.patch \
        file://0021-pxa168-add-avengers-board-support.patch \
        file://0022-pxa168-add-samsung-2Gib-nand-flash-with-id-DAEC.patch \
        file://0023-pxa168-fixed-one-build-error-on-samsung-2Gib-nand.patch \
        file://0024-pxa168-add-switch-download-interfaces-and-set-IP-ad.patch \
        file://0025-pxa168-update-machine-to-align-with-.28-kernel.patch \
        file://0026-pxa168-select-marvell-id.patch \
        file://0027-pxa910-add-TTC-DKB-board-support.patch \
        file://0028-pxa910-fix-the-TTC_DKB-mach-id-to-sync-with-linux-2.patch \
        file://0029-pxa168-disable-L2-as-sram-feature.patch \
        file://0030-pxa910-correct-usb-download-initilizaion-fail.patch \
        file://0031-pxa910-prolong-the-boot-delay-to-10s.patch \
        file://0032-pxa910-add-auto-boot-for-ttc-dkb.patch \
        file://0033-pxa910-add-autoboot-with-flash-and-image-type-check.patch \
        file://0034-pxa910-add-autoboot-check-for-all-pxa910-series.patch \
        file://0035-pxa168-Remove-the-1.3-Core-Voltage-initialization-c.patch \
        file://0036-pxa168-Remove-initialization-code-to-set-PMIC-V7-re.patch \
        file://0037-pxa168-Modified-the-aspen_init.S-to-make-it-EABI-Co.patch \
        file://0038-pxa910-basic-DVFM-support.patch \
        file://0039-pxa910-change-tftp-command-to-tftpboot-for-history.patch \
        file://0040-pxa910-fix-telephony-failure-issue.patch \
        file://0041-sync-with-.28-kernel.patch \
        file://0042-pxa910-change-common-file-to-board-directory.patch \
        file://0043-pxa910-add-readsl-and-writesl-support.patch \
        file://0044-pxa910-mlc-atom-operation-ok.patch \
        file://0045-pxa910-add-samsung-2Gbit-nand.patch \
        file://0046-pxa168-nand-driver-rearch.patch \
        file://0047-pxa168-bad-block-management-rearch.patch \
        file://0048-pxa168-eliminate-onenand-config-from-aspen.patch \
        file://0049-modify-the-uboot-nand-kernel-image-allocation-for-av.patch \
        file://0050-pxa910-onenand_base-sync-with-.28-kernel.patch \
        file://0051-pxa910-fix-onenand-write-memory-align-32-bug.patch \
        file://0052-pxa910-add-onenand-bbm-support.patch \
        file://0053-pxa168-fix-for-system-hang-bug.patch \
        file://0054-pxa168-add-workaround-for-WRCMDREQ-issue-in-R0.patch \
        file://0055-pxa168-nand-erase-command-must-add-parameters.patch \
        file://0056-pxa168-fix-nand-write-exceed-the-specified-length-w.patch \
        file://0057-pxa-read-back-an-existed-MFPR-register-instead-of-r.patch \
        file://0058-pxa910-adjust-ddr-setting-for-better-performance.patch \
        file://0059-pxa910-enable-voltage-change-on-ttc_dkb-platform.patch \
        file://0060-pxa910-set-default-voltage-to-1300mV-on-tavorevb-an.patch \
        file://0061-pxa910-adjust-ddr-setting-for-better-performance-on.patch \
        file://0062-pxa910-recover-the-percentage-show-and-yaffs-writin.patch \
        file://0063-pxa910-add-verify-function-for-yaffs-image-in-onena.patch \
        file://0064-pxa910-fix-yaffs-write-bug-with-.28-kernel-onenand.patch \
        file://0065-pxa168-change-mtd-page-and-size-calculation-way.patch \
        file://0066-pxa168-show-the-nand-writing-process.patch \
        file://0067-pxa168-add-nand-chip-sensing-capability.patch \
        file://0068-pxa168-add-temporary-workaround-for-limited-64bit-s.patch \
        file://0069-pxa168-update-mtd-to-support-64bit.patch \
        file://0070-pxa168-fix-typo-error.patch \
        file://0071-pxa168-fix-printf-64bit-output-bug.patch \
        file://0072-update-nand.h-to-support-address-more-than-0x8000000.patch \
        file://0073-pxa3xx_nand-sync-with-nand_base-in-ECC-handling.patch \
        file://0074-pxa3xx_nand-move-write-ECC-control-into-write_page_.patch \
        file://0075-cmd_nand-add-nand-biterr-function.patch \
        file://0076-add-saveenv-for-avengers.patch \
        file://0077-add-netconsole-function-to-support-FASTBOOT.patch \
        file://0078-nand-add-read-disturbance-recovery.patch \
        file://0079-enlarge-avengers-malloc-poll.patch \
        file://0080-pxa-add-micron2GbX16-nand-support.patch \
        file://0081-avengers-put-kernel-image-on-MLC-side.patch \
        file://0082-nand-sync-with-kernel.patch \
        file://0083-pxa168-align-avengers-a-ip-address-of-usb-eth-with.patch \
        file://0084-bbm-correct-bbm-behavior-when-erase-meet-bad-block.patch \
        file://0085-nand-fix-nand-sensing-bug.patch \
        file://0086-aspen-add-saveenv-function-for-zylonite2-and-aspeni.patch \
        file://0087-pxa168-lowering-RTC-setting-could-improve-Vmin.patch \
        file://0088-levente-enable-ttc-mode.patch \
        file://0089-levante-disable-long-time-on-key-pressing.patch \
        file://0090-pxa-fix-issue-of-i2c-read-write-failure-due-to-time.patch \
        file://0091-fix-netconsole-hang-bug-when-edit-the-command.patch \
        file://0092-netconsole-fix-autoboot-freeze-when-using-net-conso.patch \
        file://0093-pxa-uart-netconsole-switch-automatically.patch \
        file://0094-pxa-change-the-usb-rx-timeot-count-back.patch \
        file://0095-pxa-fix-usb-download-performance-downgrade.patch \
        file://0096-pxa910-add-ethernet-support-on-DKB-board.patch \
        file://0097-netconsole-fix-tftp-error.patch \
        file://0098-pxa-fix-build-problem-while-disable-net-console.patch \
        file://0099-usb-add-timeout-for-check-usb-connection.patch \
        file://0100-pxa-disable-levante-ttc-mode-by-default.patch \
        file://0101-ttc_dkb-disable-LDO5-turn-on-off-by-LDO3_EN.patch \
        file://0102-pxa168-fix-erase-timeout-in-R0-silicon.patch \
        file://0103-pxa910-re-write-do_read-routine.patch \
        file://0104-pxa168-enable-voltage-change-on-aspenite-and-zyloni.patch \
        file://0105-pxa168-basic-DVFM-support.patch \
        file://0106-pxa168-quick-hibernate-test.patch \
        file://0107-pxa168-enable-PMU-user-access.patch \
        file://0108-pxa168-add-i2cinit-and-i2cbase-command.patch \
        file://0109-pxa168-add-dummy-write-when-accessing-max8660-PMIC.patch \
        file://0110-pxa168-fix-unknown-nand-crash-error-and-add-0xd3ec.patch \
        file://0111-nand-sync-nand-code-with-kernel-in-dma-handling.patch \
        file://0112-pxa3xx_nand-sync-with-kernel.patch \
        file://0113-nand-if-erase-fail-then-relocate-it-on-the-fly.patch \
        file://0114-soc-add-tavorpv2-platform-support.patch \
        file://0115-tavorpv2-enable-smc-when-start-from-flash.patch \
        file://0116-soc-add-tavor-pv-support.patch \
        file://0117-mmc-add-mmc-framework-and-support-old-mmc-IP.patch \
        file://0118-tftp-revert-timeout-setting.patch \
        file://0119-netconsole-enable-netconsole-for-avengers.patch \
        file://0120-pxa168-update-hibernate-process.patch \
        file://0121-pxa168-use-ADTV1-as-VCC_APPS-for-aspenite.patch \
        file://0122-console-disbale-repeatable-command-by-default.patch \
        file://0123-pxa950-update-mach-id-for-tavorevb3-on-2.6.29.patch \
        file://0124-pv2-increase-the-timeout-in-tftp.patch \
        file://0125-pxa910-enable-timer-match-interrupt.patch \
        file://0126-pxa910-add-releasecp-command.patch \
        file://0127-pxa910-enable-system-sleep-and-rtc-wakeup.patch \
        file://0128-sf-always-read-5-bytes-for-the-idcode.patch \
        file://0129-sf-set-common-timeouts-in-seconds-not-milliseconds.patch \
        file://0130-sf-new-Macronix-MX25xx-SPI-flash-driver.patch \
        file://0131-sf-Macronix-additional-chips-supported.patch \
        file://0132-Command-for-accessing-serial-flash-update.patch \
        file://0133-spi-add-spi-simulating-driver-using-pxa-ssp.patch \
        file://0134-nand-eliminate-pxa3xx-nand-compile-warnnings.patch \
        file://0135-eliminate-compile-warnings.patch \
        file://0136-nand-fix-read-4K-page-NAND-bug-intro-by-eliminate-w.patch \
        file://0137-uboot-clean-build-warnings-in-usbeth-code.patch \
        file://0138-nand-add-ba2c-nand-id-support.patch \
        file://0139-pxa920-set-usb-to-full-speed-on-TD.patch \
        file://0140-fix-onenand-build-bug-after-eliminate-warning.patch \
        file://0141-nand-fix-page-allocation-bug-for-4K-or-large-page.patch \
        file://0142-gpio-enable-gpio-clock-for-aspenite-and-avengers.patch \
        file://0143-aspen-enlarge-default-malloc-space.patch \
        file://0144-pxa168-enable-uart-usb-clk-in-avengers_pxa168.c.patch \
        file://0145-disable-ethnet-for-avengers.patch \
        file://0146-enable-all-uart-clk.patch \
        file://0147-uart2-mfp-config.patch \
        file://0148-add-spi-support-for-avengers_lite-above-1.6q.patch \
        file://0149-spi-add-release-method-for-spi-flash.patch \
        file://0150-disable-console-only-for-aspenite-when-using-spi-nor.patch \
        file://0151-fix-auto-boot-from-nand-in-avengers-lite-1.6f.patch \
        file://0152-pxa688-initial-mmp2-support.patch \
        file://0153-pxa688-add-cache-flush-all-replacement.patch \
        file://0154-pxa688-add-flint-and-jasper-basic-support.patch \
        file://0155-pxa688-add-micron-8Gx8-nand-support.patch \
        file://0156-pxa688-sync-nand-with-master.patch \
        file://0157-pxa688-update-timer-to-6.5M-and-nand-configure.patch \
        file://0158-pxa688-add-nand-support-on-flint.patch \
        file://0159-pxa688-add-bonnell-support-with-autoboot.patch \
        file://0160-pxa688-use-CPU-400MHz-as-default-for-Bonnell.patch \
        file://0161-pxa688-move-freq-code-to-sram-and-add-ddr-calibrati.patch \
        file://0162-pxa688-enable-commands-in-freq.c.patch \
        file://0163-pxa688-fix-nand-timeout-error-on-flint-board.patch \
        file://0164-pxa688-enable-flint-autoboot.patch \
        file://0165-pxa688-code-clean-for-flint.patch \
        file://0166-pxa688-add-Bonnell-mmc3-support.patch \
        file://0167-pxa688-add-Bonnell-eMMC-support-with-bootstrap-work.patch \
        file://0168-pxa688-enable-4bit-mode-for-eMMC-on-Bonnell.patch \
        file://0169-pxa688-add-op2-support-for-624-400-200.patch \
        file://0170-pxa688-use-more-aggressive-setting-for-op2.patch \
        file://0171-pxa688-add-op3-for-400CPU-400DDR-200AXI-546GPU.patch \
        file://0172-pxa688-use-fastbank-for-better-performance.patch \
        file://0173-pxa688-move-sram-address-to-avoid-WTM-conflict.patch \
        file://0174-pxa688-update-DDR-setting-for-Z1-chip.patch \
        file://0175-pxa688-sync-flash-driver-with-master.patch \
        file://0176-pxa688-update-USB-PHY-setting.patch \
        file://0177-pxa688-update-DDR-setting-for-400MHz.patch \
        file://0178-pxa688-update-op2-for-Z1-chip.patch \
        file://0179-pxa688-add-voltage-change-support-on-Bonnell-and-co.patch \
        file://0180-pxa688-update-NAND-ECC-judgment.patch \
        file://0181-pxa688-add-eMMC-PRV-info-to-console.patch \
        file://0182-pxa688-add-elpdia-512M-ddr-support-and-use-op2-as-d.patch \
        file://0183-pxa688-update-eMMC-info-print-on-console.patch \
        file://0184-pxa688-disable-MMC-SD-dynamic-clock-gate.patch \
        file://0185-pxa688-increase-core-voltage-to-1280mv-on-Z1.patch \
        file://0186-pxa688-tune-Elpida-DDR-setting.patch \
        file://0187-SD-card-Fix-a-bug-to-compute-the-clock-of-MM4CLK-pi.patch \
        file://0188-pxa688-fix-mmc-capacity-length-bug.patch \
        file://0189-pxa688-add-ext2load-and-fatload-from-external-SD-ca.patch \
        file://0190-pxa688-fix-mips-bug-on-mmp2.patch \
        file://0191-pxa688-remove-mmc-bus-test.patch \
        file://0192-pxa688-always-boot-kernel-from-emmc-partition-0.patch \
        file://0193-mmp2-passing-ddr-type-to-kernel.patch \
        file://0194-mmp2-move-bi_boot_params-addr-to-0x3C00.patch \
        file://0195-mmp2-modify-emmc-autoboot-to-suit-larger-kernel.patch \
        file://0196-ARM-fix-build-error-with-marvell-gcc-4.4.4.patch \
        file://0197-gcc-fix-for-gcc-4.4.4-boot-up-failure.patch \
        file://0198-mmp2-create-marvell-specific-tag-to-pass-ddr-type.patch \
        file://0199-mmp2-re-structure-ddr-setting.patch \
        file://0200-mmp2-fix-assembly-code-bug-for-r0-usage.patch \
        file://0201-mmp2-support-eMMC-4.4.patch \
        file://0202-emmc-init-bus_width-to-1-as-init.patch \
        file://0203-mmp2-no-loner-enabling-vmeta-clock-in-u-boot.patch \
        file://0204-mmp2-add-brownstone-support.patch \
        file://0205-mmp2-disable-dualissuse-for-co-processor-on-Z0-Z1-s.patch \
        file://0206-mmp2-add-mmp2-stepping-print.patch \
          "

S = "${WORKDIR}/uboot"


